App\Entity\Pessoas\Documento:
    type: entity
    table: pessoas.documento
    indexes:
        IDX_93F45BE03AE81E6F:
            columns:
                - id_pessoa
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        tipo:
            type: pessoas.tipo_documento
            nullable: false
        dataCadastro:
            type: datetime
            nullable: false
            column: data_cadastro
        valor:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: valor
    manyToOne:
        pessoa:
            targetEntity: App\Entity\Pessoas\Pessoa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pessoa:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
