App\Entity\Pessoas\Endereco:
    type: entity
    table: pessoas.endereco
    indexes:
        IDX_D24751BC3AE81E6F:
            columns:
                - id_pessoa
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        tipo:
            type: pessoas.tipo_endereco_pessoa
            nullable: false
        pais:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        estado:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        uf:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        cidade:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        bairro:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        logradouro:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        numero:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        cep:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        localizacao:
            type: point
            nullable: true
            requireSQLConversion: true
        complemento:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        idPessoa:
            targetEntity: App\Entity\Pessoas\Pessoa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pessoa:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
