App\Entity\Pessoas\PessoaToPessoa:
    type: entity
    table: pessoas.pessoa_to_pessoa
    indexes:
        IDX_DAD942506F46B572:
            columns:
                - id_pessoa
        IDX_DAD94250E7747ECD:
            columns:
                - id_relacao
    id:
        tipo:
            type: pessoas.tipo_relacionamento_pessoa
            nullable: false
            id: true
        pessoa:
            associationKey: true
        relacao:
            associationKey: true
    manyToOne:
        pessoa:
            targetEntity: App\Entity\Pessoas\Pessoa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pessoa:
                    referencedColumnName: id
            orphanRemoval: false
        relacao:
            targetEntity: App\Entity\Pessoas\Pessoa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_relacao:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
